const courseData =[
    {value: "CH101", label: "CH101 Introduction to Chemical Engineering" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH201", label: "CH201 Thermodynamics" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH202", label: "CH202 Transport Phenomena" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH230", label: "CH230 Chemical Engineering Simulation Laboratory (Lab I)" ,lecture :0,tutorial:0, practical:4, selfStudy:2, credits:2},
    {value: "CH120", label: "CH120 Seminar I" ,lecture :0,tutorial:0, practical:2, selfStudy:1, credits:1},
    {value: "CH203", label: "CH203 Heat and Mass transfer" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH204", label: "CH204 Fluid Mechanics" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH231", label: "CH231 Fluid Flow, Heat and Mass Transfer Laboratory (Lab II)" ,lecture :0,tutorial:0, practical:4, selfStudy:2, credits:2},
    {value: "CH220", label: "CH220 Seminar II (Data Analysis and Research Skill)" ,lecture :0,tutorial:0, practical:2, selfStudy:1, credits:1},
    {value: "CH301", label: "CH301 Separation Processes" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH302", label: "CH302 Chemical Reaction Engineering" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH303", label: "CH303 Chemical Process Control" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH330", label: "CH330 Chemical Reaction Engineering Laboratory (Lab III)" ,lecture :0,tutorial:0, practical:4, selfStudy:2, credits:2},
    {value: "CH320", label: "CH320 Seminar III (Chemical Engineering Applications)" ,lecture :0,tutorial:0, practical:2, selfStudy:1, credits:1},
    {value: "CH304", label: "CH304 Process Equipment Design" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH305", label: "CH305 Process Design and Economics" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH331", label: "CH331 Chemical Process Control Laboratory (Lab IV)" ,lecture :0,tutorial:0, practical:4, selfStudy:2, credits:2},
    {value: "CH420", label: "CH420 Seminar IV (Aspects of Chemical Business and Ethics)" ,lecture :0,tutorial:0, practical:2, selfStudy:1, credits:1},
    {value: "CP301", label: "CP301 Development Engineering Project" ,lecture :0,tutorial:0, practical:6, selfStudy:3, credits:3},
    {value: "CH603", label: "CH603 Engineering Application of Rheology" ,lecture :3,tutorial:0, practical:0, selfStudy:7, credits:4},
    {value: "CH604", label: "CH604 Chemical Reactor Analysis and Design" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH605", label: "CH605 Heterogeneous catalysis and catalytic reactors" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH606", label: "CH606 Introduction To Molecular Dynamics " ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH607", label: "CH607 Water Treatment" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH608", label: "CH608 Statistics For Chemical Engineers" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH609", label: "CH609 Modelling of Chemical Engineering System" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH612", label: "CH612 Interfacial Engineering" ,lecture :3,tutorial:0, practical:0, selfStudy:6, credits:3},
    {value: "CH613", label: "CH613 Micro Rheology" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH614", label: "CH614 CFD of Multi phase System" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH615", label: "CH615 Fundamental of Particle Suspension " ,lecture :3,tutorial:0, practical:0, selfStudy:6, credits:3},
    {value: "CH616", label: "CH616 Introduction to Bio-Rheology" ,lecture :2,tutorial:0, practical:2, selfStudy:5, credits:3},
    {value: "CH502", label: "CH502 Fundamental of Particle Technology" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH503", label: "CH503 Fundamental and Applications of Microfluidics" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH504", label: "CH504 Numerical Methods for Engineers" ,lecture :3,tutorial:0, practical:2, selfStudy:7, credits:4},
    {value: "CH505", label: "CH505 Introduction to Multiphase Flow" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH506", label: "CH506 Chemical Process Safety" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "CH507", label: "CH507 Introduction to Polymer Science and Engineering" ,lecture :3,tutorial:0, practical:0, selfStudy:6, credits:3},
    {value: "CH512", label: "CH512 Machine Learning Applications for Process Engineering" ,lecture :3,tutorial:1, practical:2, selfStudy:6, credits:4},
    {value: "GE111", label: "GE111 Introduction to Environmental Science and Engineering" ,lecture :3,tutorial:1, practical:0, selfStudy:5, credits:3},
    {value: "GE109", label: "GE109 Introduction to Engineering Products" ,lecture :0,tutorial:0, practical:2, selfStudy:1, credits:1},
    {value: "GE101", label: "GE101 Technology Museum Lab" ,lecture :0,tutorial:0, practical:2, selfStudy:1, credits:1},
]

export default courseData